name: Release

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create release"
        required: false
        default: true
        type: boolean
      tags:
        description: "tag"
        required: true
        type: string

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Release tag
        id: releasetag
        run: echo "release_tag=${{ github.event.inputs.tags }}" >> $GITHUB_OUTPUT

      - name: Set Git tag
        if: ${{ github.event.inputs.create_release == 'true' && success() }}
        run: |
          git tag ${{ steps.releasetag.outputs.release_tag }}
          git push origin ${{ steps.releasetag.outputs.release_tag }}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.releasetag.outputs.release_tag }} \
            --generate-notes
